users:
  - name: user4
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62323061383437623631316563666632623137386232616334336165326164346631323937303665
          3061316235356163666439356531353935343133303861650a643464383337616133316464626263
          65613930663963643162646331306164653162386634356338643533353364613762653432393439
          3734653865306339350a303963643634306463666134663839626366303730656666343330633031
          35643666636637343366653639323030663234303338646165313465663937613361
  - name: user5
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62323061383437623631316563666632623137386232616334336165326164346631323937303665
          3061316235356163666439356531353935343133303861650a643464383337616133316464626263
          65613930663963643162646331306164653162386634356338643533353364613762653432393439
          3734653865306339350a303963643634306463666134663839626366303730656666343330633031
          35643666636637343366653639323030663234303338646165313465663937613361
  - name: user6
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62323061383437623631316563666632623137386232616334336165326164346631323937303665
          3061316235356163666439356531353935343133303861650a643464383337616133316464626263
          65613930663963643162646331306164653162386634356338643533353364613762653432393439
          3734653865306339350a303963643634306463666134663839626366303730656666343330633031
          35643666636637343366653639323030663234303338646165313465663937613361