# Project information
site_name: 'Ansible Course'
site_description: 'Internal Ansible Course for DIPS AS'
site_author: 'Andreas Mosti / Tord Heimdal'
site_url: 'https://github.com/DIPSAS/AnsibleCourse'

# Navigation
nav: 
  - Home: index.md
  - Exercises: 
    - '01: Inventory' : exercises/01-Inventory.md
    - '02: First Playbook' : exercises/02-FirstPlaybook.md
    - '03: Roles' : exercises/03-Roles.md
    - '05: DIPS Configuration Server ' : exercises/05-ConfigurationServer.md

# Repository
repo_name: 'DIPSAS/AnsibleCourse'
repo_url: 'https://github.com/DIPSAS/AnsibleCourse'


# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/DIPSAS'
    - type: 'twitter'
      link: 'https://twitter.com/dipsasa'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true