# Denne feilet på første forsøk, da en av avhengighetene ikke ble installert. Men ved neste forsøk, så ble den grønn fordi den fant ut at den allerede var installert.
- name: Install Dotnet Framework 4.6.2
  win_chocolatey:
    name: dotnet4.6.2
    state: present
  register: install_status
  tags: dotnet4.6.2

- name: Reboot after install
  win_reboot:
  when: install_status.changed
  tags: dotnet4.6.2