configServerPacakgeSource: http://dips-nuget/nuget/Arena-17.2-Choco/
configServerPackageName: DIPS-Arena-Configuration-Server-IIS
configServerPackageVersion: 1.2.52

configServerInstallLocation: C:\\DIPS
configServerUseClientCertificate: false